"""Minimal SVG chart renderer for report-friendly anomaly timelines."""

from __future__ import annotations

from pathlib import Path

import numpy as np


def write_timeline_svg(
    path: str | Path,
    primary_metric: np.ndarray,
    scores: np.ndarray,
    threshold: float,
    labels: np.ndarray | None,
    predictions: np.ndarray,
    title: str = "DADA-Lite KPI Anomaly Detection",
) -> None:
    metric = _normalize(np.asarray(primary_metric, dtype=float).reshape(-1))
    score_values = _normalize(np.asarray(scores, dtype=float).reshape(-1))
    pred = np.asarray(predictions, dtype=int).reshape(-1)
    truth = np.asarray(labels, dtype=int).reshape(-1) if labels is not None else None
    threshold_norm = float(_normalize(np.asarray([0.0, threshold, np.max(scores)], dtype=float))[1])

    width = 1100
    height = 620
    margin_left = 70
    plot_width = width - 120
    top_y = 95
    mid_y = 335
    panel_height = 170

    metric_polyline = _polyline(metric, margin_left, top_y, plot_width, panel_height)
    score_polyline = _polyline(score_values, margin_left, mid_y, plot_width, panel_height)
    threshold_y = mid_y + panel_height - threshold_norm * panel_height

    truth_rects = _event_rects(truth, margin_left, top_y, plot_width, panel_height * 2 + 70, "#f7a8b8") if truth is not None else ""
    pred_rects = _event_rects(pred, margin_left, top_y, plot_width, panel_height * 2 + 70, "#ff7f50", opacity="0.20")

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" fill="#ffffff"/>
  <text x="{margin_left}" y="45" font-family="Arial, sans-serif" font-size="24" font-weight="700" fill="#17202a">{_escape(title)}</text>
  <text x="{margin_left}" y="72" font-family="Arial, sans-serif" font-size="13" fill="#5d6d7e">pink = labeled fault interval, orange = predicted anomaly interval</text>
  {truth_rects}
  {pred_rects}
  <line x1="{margin_left}" y1="{top_y + panel_height}" x2="{margin_left + plot_width}" y2="{top_y + panel_height}" stroke="#d5d8dc"/>
  <line x1="{margin_left}" y1="{mid_y + panel_height}" x2="{margin_left + plot_width}" y2="{mid_y + panel_height}" stroke="#d5d8dc"/>
  <text x="18" y="{top_y + 85}" font-family="Arial, sans-serif" font-size="13" fill="#34495e">KPI</text>
  <text x="18" y="{mid_y + 85}" font-family="Arial, sans-serif" font-size="13" fill="#34495e">score</text>
  <polyline points="{metric_polyline}" fill="none" stroke="#2e86c1" stroke-width="2"/>
  <polyline points="{score_polyline}" fill="none" stroke="#884ea0" stroke-width="2"/>
  <line x1="{margin_left}" y1="{threshold_y:.2f}" x2="{margin_left + plot_width}" y2="{threshold_y:.2f}" stroke="#c0392b" stroke-width="2" stroke-dasharray="7,6"/>
  <text x="{margin_left + plot_width - 120}" y="{threshold_y - 8:.2f}" font-family="Arial, sans-serif" font-size="12" fill="#c0392b">threshold</text>
  <text x="{margin_left}" y="{height - 35}" font-family="Arial, sans-serif" font-size="12" fill="#566573">Generated by member_e_dada/scripts/run_dada_lite.py</text>
</svg>
"""
    Path(path).write_text(svg, encoding="utf-8")


def _normalize(values: np.ndarray) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    min_value = float(np.min(arr))
    max_value = float(np.max(arr))
    if max_value - min_value < 1e-12:
        return np.zeros_like(arr)
    return (arr - min_value) / (max_value - min_value)


def _polyline(values: np.ndarray, left: int, top: int, width: int, height: int) -> str:
    n = len(values)
    if n == 1:
        return f"{left},{top + height}"
    points = []
    for index, value in enumerate(values):
        x = left + width * index / (n - 1)
        y = top + height - float(value) * height
        points.append(f"{x:.2f},{y:.2f}")
    return " ".join(points)


def _event_rects(
    flags: np.ndarray | None,
    left: int,
    top: int,
    width: int,
    height: int,
    color: str,
    opacity: str = "0.28",
) -> str:
    if flags is None or len(flags) == 0:
        return ""
    flags = np.asarray(flags, dtype=int)
    n = len(flags)
    rects = []
    start = None
    for index, flag in enumerate(flags.tolist() + [0]):
        if flag == 1 and start is None:
            start = index
        if flag == 0 and start is not None:
            end = index
            x = left + width * start / max(1, n - 1)
            rect_width = max(2.0, width * (end - start) / max(1, n - 1))
            rects.append(
                f'<rect x="{x:.2f}" y="{top}" width="{rect_width:.2f}" height="{height}" fill="{color}" opacity="{opacity}"/>'
            )
            start = None
    return "\n  ".join(rects)


def _escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

